---
title: "Lab 02 - Global plastic waste"
author: "Team Name: Sophie, Lucia, Andy, Nathan"
date: "`r Sys.Date()`"
output: html_document
---

### Load packages and data

```{r load-packages, message = FALSE, warning=FALSE}
library(tidyverse)
library(readxl)
```


## Load & join data sets

```{r load-data, message = FALSE}
# Member 2 (pair 1) write code to load File 1 data here:
mismanaged_plastic_waste_per_capita <- read_csv("data/mismanaged-plastic-waste-per-capita.csv")

mismanaged_plastic_waste_per_capita 

# Member 4 (pair 2) write code to load File 2 data here:
per_capita_ocean_plastic_waste<-read_csv("data/per-capita-ocean-plastic-waste.txt")

per_capita_ocean_plastic_waste

# Member 1 (pair 1) write code to load File 3 data here:
UN_country_population<-read_csv("data/UN_country_population.tsv")

UN_country_population

# Member 3 (pair 2) write code to load File 4 data here:
UN_country_region <- read_excel("data/UN_country_region.xlsx")

UN_country_region

```



```{r join-data, message = FALSE}
# Member 2 (pair 1) write code to create object 'plastic_data_all':
data1 <- read_csv("data/mismanaged-plastic-waste-per-capita.csv")
plastic_data_all <- data1
plastic_data_all %>% head(n = 10)

# Member 4 (pair 2) write code to join your data to 'plastic_data_all':
data2 <- read_csv2("data/per-capita-ocean-plastic-waste.txt")

plastic_data_all <- data2 %>%
  select(-name) %>%
  left_join(plastic_data_all, by = "code")

# Member 1 (pair 1) write code to join your data to 'plastic_data_all':
data3 <- read_tsv("data/UN_country_population.tsv")
plastic_data_all <- data3 %>%
  select(-name) %>%
  right_join(plastic_data_all, by = "code")


# Member 3 (pair 2) write code to join your data to 'plastic_data_all':
data4 <- read_excel("data/UN_country_region.xlsx")
plastic_data_all <- data4 %>%
  select(-name) %>%
  right_join(plastic_data_all, by = "code")

```


```{r print-data, message = FALSE}
# Member 2 (pair 1) adds code here to view the first 10 rows of 'plastic_data_all'
plastic_data_all%>%head(n=10)


```



## Exercises

### Ex 1.

```{r Ex1, message = FALSE}
# Write your code here to answer exercise 1
coastal_countries <- data1
coastal_countries %>% head()


```



### Ex 2.

```{r Ex2, message = FALSE}
# Write your code here to answer exercise 2



```


### Ex 3.

```{r Ex3, message = FALSE}
# Write your code here to answer exercise 3



```


### Ex 4.

```{r Ex4, message = FALSE}
# Write your code here to answer exercise 4



```
